import React, { createContext, useContext, useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';


export const lightTheme = {
  isDark: false,
  bg: '#fafafa',
  cardBg: '#fff',
  text: '#111',
  subText: '#555',
  border: '#eee',
  inputBg: '#f5f5f5',
  headerBg: '#fff',
  sectionTitle: '#888',
  itemBg: '#fff',
  iconColor: '#444',
  switchTrackOff: '#ddd',
  switchTrackOn: '#6366f1',
  primary: '#6366f1',
  accent: '#3b82f6',
  success: '#22C55E',
  warning: '#F59E0B',
  error: '#EF4444',
  primaryLight: '#eef2ff',
  drawerHeaderBg: '#6366f1',
  statCardTotal: '#1a1a2e',
  statCardCompleted: '#1a472a',
  statCardPending: '#5a2d00',
  statCardMissed: '#5a0a0a',
  // Home screen
  topBg: '#dbeafe',
  menuButtonBg: '#fff',
  menuButtonBorder: '#ececec',
  helloText: '#111',
  statTotal: '#fff',
  statCompleted: '#dff8de',
  statPending: '#dff3ff',
  statMissed: '#ffd7d7',
  statNumber: '#111',
  statLabel: '#333',
  progressCardBg: '#fff',
  progressTitle: '#111',
  progressSubText: '#666',
  progressBadgeBg: '#e0e7ff',
  progressBarTrack: '#eef2ff',
  progressBadgeText: '#4f46e5',
  calendarLink: '#6366f1',
  avatarBg: '#e0e7ff',
  avatarBorder: '#c7d2fe',
  avatarText: '#4338ca',
  menuIcon: '#6366f1',
  menuIconActive: '#4f46e5',
  modalHandle: '#cbd5e1',
  legendDotPrimary: '#6366f1',
  legendDotSelected: '#a5b4fc',
  legendDotToday: '#dbeafe',
  selectedDayBg: '#6366f1',
  todayDayBg: '#dbeafe',
  taskDot: '#6366f1',
  selectedTasksCountBg: '#e0e7ff',
  selectedTasksCountText: '#4f46e5',
  goToDateBtnBg: '#6366f1',
  fabBg: '#6366f1',
  fabLabelText: '#4f46e5',
  pendingBadgeBg: '#dff3ff',
  pendingBadgeText: '#126a8a',
  completedBadgeBg: '#dff8de',
  completedBadgeText: '#1f7a31',
  missedBadgeBg: '#fde8e8',
  missedBadgeText: '#c0392b',
  dateChipActiveBg: '#111',
  filterChipActiveBg: '#111',
  drawerActiveTint: '#6366f1',
  drawerInactiveTint: '#111',
  calendarCardBg: '#fff',
  calendarTitle: '#111',
  dateChipBg: '#f5f7ff',
  dateChipBorder: '#e0e7ff',
  mainCardBg: '#c7d2fe',
  cardTitleText: '#111',
  cardDateText: '#555',
  aiPillBg: '#fef3c7',
  aiPillText: '#111',
  addPillBg: '#fff',
  addPillText: '#111',
  filterChipBg: 'rgba(255,255,255,0.58)',
  filterChipBorder: 'rgba(17,17,17,0.08)',
  filterText: '#111',
  taskCardBg: '#fff',
  taskCardBorder: '#ececec',
  taskTitle: '#111',
  taskTime: '#666',
  tipCardBg: '#fff',
  tipCardBorder: '#ececec',
  tipTitle: '#111',
  tipText: '#555',
  emptyCardBg: '#fff',
  emptyCardBorder: '#ececec',
  emptyTitle: '#111',
  emptyText: '#666',
  modalSheetBg: '#fff',
  modalTitle: '#111',
  weekHeaderText: '#777',
  dayNumber: '#111',
  otherMonthText: '#bbb',
  legendText: '#666',
  selectedTasksBg: '#f5f7ff',
  selectedTasksBorder: '#e0e7ff',
  selectedTasksTitle: '#111',
  selectedTasksDate: '#666',
  modalTaskTitle: '#111',
  modalTaskTime: '#666',
  modalTaskBorder: '#eee',
  drawerBg: '#fff',
  menuItemBg: 'transparent',
  menuItemActiveBg: '#eef2ff',
  menuIconWrapBg: '#eef2ff',
  menuText: '#111',
  fabLabelBg: '#ffffff',
  fabLabelBorder: '#c7d2fe',
  quickActionsBg: '#fff',
  quickActionsBorder: '#e0e7ff',
  quickActionText: '#111',
  quickActionIconBg: '#eef2ff',
  // Today Plan screen
  planContainerBg: '#fff',
  planTopShapeBg: '#dbeafe',
  planTitle: '#111',
  planSubtitle: '#666',
  dateCardBg: '#fff',
  dateCardBorder: '#c7d2fe',
  dateIconWrapBg: '#e0e7ff',
  dateLabel: '#777',
  dateValue: '#111',
  changeDateBtnBg: '#fef3c7',
  changeDateBtnText: '#111',
  highlightCardBg: '#e0e7ff',
  highlightTitle: '#111',
  highlightText: '#444',
  percentBg: '#fff',
  percentValue: '#111',
  percentLabel: '#666',
  progressFill: '#6366f1',
  progressTrack: '#eef2ff',
  calendarBg: '#FFFFFF',
  calendarSelectedBg: '#a5b4fc',
  calendarTodayText: '#6366f1',
  calendarDot: '#6366f1',
  calendarHeaderText: '#4338ca',
  calendarDisabledText: '#c7d2fe',
  filterBorder: '#111',
  filterBg: '#fff',
  activeFilterBg: '#c7d2fe',
  timelineTime: '#666',
  timelineDot: '#6366f1',
  timelineLine: '#c7d2fe',
  timelineCardBg: '#f5f7ff',
  timelineCardBorder: '#c7d2fe',
  iconBoxBg: '#e0e7ff',
  planTitleText: '#111',
  planNoteText: '#555',
  planScheduleDate: '#4338ca',
  planPrimaryBtnText: '#4f46e5',
  primaryBtnBg: '#fff',
  primaryBtnBorder: '#111',
  // Add Task screen
  addTaskContainerBg: '#f5f7ff',
  addTaskTopShape: '#dbeafe',
  addTaskTitle: '#111',
  addTaskSubtitle: '#666',
  addTaskCardBg: '#fff',
  addTaskCardBorder: '#c7d2fe',
  addTaskCardTitle: '#111',
  addTaskIconBoxBg: '#eef2ff',
  addTaskChipSelectedBg: '#eef2ff',
  addTaskChipSelectedBorder: '#6366f1',
  addTaskBtnBg: '#6366f1',
  addTaskInputBg: '#FFFFFF',
  addTaskInputBorder: '#c7d2fe',
  addTaskInputText: '#111',
  addTaskFieldLabel: '#444',
  addTaskChipBg: '#fff',
  addTaskChipBorder: '#D8D4D9',
  addTaskChipText: '#111',
  addTaskNoteInputBg: '#fff',
  addTaskNoteInputBorder: '#c7d2fe',
  addTaskCountText: '#777',
  addTaskReminderText: '#555',
  // Tasks screen
  tasksContainerBg: '#f5f7ff',
  tasksHeaderBg: '#4338ca',
  tasksIconBtnBg: '#eef2ff',
  tasksSummaryTotalBg: '#eef2ff',
  tasksSummaryCompletedBg: '#f0fdf4',
  tasksSummaryTotalIconBg: '#dbeafe',
  tasksSummaryCompletedIconBg: '#dcfce7',
  tasksActiveFilterBg: '#6366f1',
  tasksTimeText: '#6366f1',
  tasksSearchBg: '#fff',
  tasksSearchBorder: '#e0e7ff',
  tasksSearchText: '#111',
  tasksItemBg: '#fff',
  tasksItemBorder: '#e0e7ff',
  tasksItemTitle: '#111',
  tasksItemNote: '#666',
  tasksItemTime: '#888',
  tasksMenuBg: '#fff',
  tasksMenuBorder: '#e0e7ff',
  tasksMenuText: '#111',
  tasksEditModalBg: '#fff',
  tasksEditModalBorder: '#e0e7ff',
  tasksEditModalTitle: '#111',
  tasksEditInputBg: '#f5f7ff',
  tasksEditInputBorder: '#e0e7ff',
  tasksEditInputText: '#111',
  tasksModalSaveBg: '#c7d2fe',
  // Edit Profile screen
  editProfileBg: '#fafafa',
  editProfileHeaderBg: '#fff',
  editProfileHeaderBorder: '#eee',
  editProfileHeaderTitle: '#111',
  editProfileBackBg: '#f5f5f5',
  editProfileGenderTitle: '#555',
  editProfileGenderCircleBg: '#e8e8e8',
  editProfileGenderText: '#333',
  // AI Scheduler screen
  aiContainerBg: '#fafafa',
  aiCardBg: '#e0e7ff',
  aiCardBorder: '#c7d2fe',
  aiText: '#111',
  aiSubText: '#555',
  aiHintBg: '#eef2ff',
  aiHintText: '#4338ca',
  aiTaskCountBg: '#dbeafe',
  aiTaskCountText: '#4f46e5',
  aiConfirmBtn: '#6366f1',
  aiIconWrapBg: '#eef2ff',
  aiDraggingCardBg: '#f5f7ff',
  aiConfidenceFill: '#6366f1',
  aiConfidenceText: '#4f46e5',
};

export const darkTheme = {
  isDark: true,
  bg: '#0f0f1a',
  cardBg: '#1e1e2e',
  text: '#f0f0f0',
  subText: '#aaa',
  border: '#333',
  inputBg: '#2a2a3a',
  headerBg: '#1a1a2a',
  sectionTitle: '#999',
  itemBg: '#1e1e2e',
  iconColor: '#bbb',
  switchTrackOff: '#444',
  switchTrackOn: '#818cf8',
  primary: '#818cf8',
  accent: '#60a5fa',
  success: '#22C55E',
  warning: '#FBBF24',
  error: '#F87171',
  primaryLight: '#1e1b4b',
  accentLight: '#1e3a5f',
  drawerHeaderBg: '#4338ca',
  statCardTotal: '#2a2a4a',
  statCardCompleted: '#1a3a28',
  statCardPending: '#3a2000',
  statCardMissed: '#3a0a0a',
  // Home screen
  topBg: '#1e1b4b',
  menuButtonBg: '#1e1e2e',
  menuButtonBorder: '#333',
  helloText: '#f0f0f0',
  statTotal: '#1e1e2e',
  statCompleted: '#1a3a28',
  statPending: '#0a2a3a',
  statMissed: '#3a0a0a',
  statNumber: '#f0f0f0',
  statLabel: '#ccc',
  progressCardBg: '#1e1e2e',
  progressTitle: '#f0f0f0',
  progressSubText: '#999',
  progressBadgeBg: '#312e81',
  progressBarTrack: '#1e1b4b',
  progressBadgeText: '#a5b4fc',
  calendarLink: '#818cf8',
  avatarBg: '#312e81',
  avatarBorder: '#4338ca',
  avatarText: '#c7d2fe',
  menuIcon: '#a5b4fc',
  menuIconActive: '#818cf8',
  modalHandle: '#475569',
  legendDotPrimary: '#818cf8',
  legendDotSelected: '#6366f1',
  legendDotToday: '#1e3a5f',
  selectedDayBg: '#6366f1',
  todayDayBg: '#1e3a5f',
  taskDot: '#818cf8',
  selectedTasksCountBg: '#312e81',
  selectedTasksCountText: '#a5b4fc',
  goToDateBtnBg: '#6366f1',
  fabBg: '#6366f1',
  fabLabelText: '#a5b4fc',
  pendingBadgeBg: '#0a2a3a',
  pendingBadgeText: '#7dd3fc',
  completedBadgeBg: '#1a3a28',
  completedBadgeText: '#86efac',
  missedBadgeBg: '#3a0a0a',
  missedBadgeText: '#fca5a5',
  dateChipActiveBg: '#6366f1',
  filterChipActiveBg: '#6366f1',
  drawerActiveTint: '#818cf8',
  drawerInactiveTint: '#f0f0f0',
  calendarCardBg: '#1e1e2e',
  calendarTitle: '#f0f0f0',
  dateChipBg: '#2a2a3a',
  dateChipBorder: '#3730a3',
  mainCardBg: '#312e81',
  cardTitleText: '#f0f0f0',
  cardDateText: '#aaa',
  aiPillBg: '#3a2a10',
  aiPillText: '#f0f0f0',
  addPillBg: '#2a2a3a',
  addPillText: '#f0f0f0',
  filterChipBg: 'rgba(255,255,255,0.08)',
  filterChipBorder: 'rgba(255,255,255,0.12)',
  filterText: '#f0f0f0',
  taskCardBg: '#1e1e2e',
  taskCardBorder: '#333',
  taskTitle: '#f0f0f0',
  taskTime: '#aaa',
  tipCardBg: '#1e1e2e',
  tipCardBorder: '#333',
  tipTitle: '#f0f0f0',
  tipText: '#aaa',
  emptyCardBg: '#1e1e2e',
  emptyCardBorder: '#333',
  emptyTitle: '#f0f0f0',
  emptyText: '#aaa',
  modalSheetBg: '#1a1a2a',
  modalTitle: '#f0f0f0',
  weekHeaderText: '#888',
  dayNumber: '#f0f0f0',
  otherMonthText: '#555',
  legendText: '#aaa',
  selectedTasksBg: '#1e1e2e',
  selectedTasksBorder: '#333',
  selectedTasksTitle: '#f0f0f0',
  selectedTasksDate: '#aaa',
  modalTaskTitle: '#f0f0f0',
  modalTaskTime: '#aaa',
  modalTaskBorder: '#333',
  drawerBg: '#1a1a2a',
  menuItemBg: 'transparent',
  menuItemActiveBg: '#312e81',
  menuIconWrapBg: '#2a2a3a',
  menuText: '#f0f0f0',
  fabLabelBg: '#1e1e2e',
  fabLabelBorder: '#333',
  quickActionsBg: '#1e1e2e',
  quickActionsBorder: '#333',
  quickActionText: '#f0f0f0',
  quickActionIconBg: '#312e81',
  // Today Plan screen
  planContainerBg: '#0f0f1a',
  planTopShapeBg: '#1e3a5f',
  planTitle: '#f0f0f0',
  planSubtitle: '#aaa',
  dateCardBg: '#1e1e2e',
  dateCardBorder: '#3730a3',
  dateIconWrapBg: '#312e81',
  dateLabel: '#aaa',
  dateValue: '#f0f0f0',
  changeDateBtnBg: '#3a2a10',
  changeDateBtnText: '#f0f0f0',
  highlightCardBg: '#312e81',
  highlightTitle: '#f0f0f0',
  highlightText: '#bbb',
  percentBg: '#1e1e2e',
  percentValue: '#f0f0f0',
  percentLabel: '#aaa',
  progressFill: '#818cf8',
  progressTrack: '#1e1b4b',
  calendarBg: '#1e1e2e',
  calendarSelectedBg: '#6366f1',
  calendarTodayText: '#818cf8',
  calendarDot: '#818cf8',
  calendarHeaderText: '#a5b4fc',
  calendarDisabledText: '#3730a3',
  filterBorder: '#555',
  filterBg: '#1e1e2e',
  activeFilterBg: '#312e81',
  timelineTime: '#aaa',
  timelineDot: '#818cf8',
  timelineLine: '#3730a3',
  timelineCardBg: '#1e1e2e',
  timelineCardBorder: '#3730a3',
  iconBoxBg: '#312e81',
  planTitleText: '#f0f0f0',
  planNoteText: '#aaa',
  planScheduleDate: '#a5b4fc',
  planPrimaryBtnText: '#a5b4fc',
  primaryBtnBg: '#1e1e2e',
  primaryBtnBorder: '#555',
  // Add Task screen
  addTaskContainerBg: '#0f0f1a',
  addTaskTopShape: '#1e3a5f',
  addTaskTitle: '#f0f0f0',
  addTaskSubtitle: '#aaa',
  addTaskCardBg: '#1e1e2e',
  addTaskCardBorder: '#3730a3',
  addTaskCardTitle: '#f0f0f0',
  addTaskIconBoxBg: '#312e81',
  addTaskChipSelectedBg: '#1e1b4b',
  addTaskChipSelectedBorder: '#818cf8',
  addTaskBtnBg: '#6366f1',
  addTaskInputBg: '#2a2a3a',
  addTaskInputBorder: '#333',
  addTaskInputText: '#f0f0f0',
  addTaskFieldLabel: '#bbb',
  addTaskChipBg: '#2a2a3a',
  addTaskChipBorder: '#444',
  addTaskChipText: '#f0f0f0',
  addTaskNoteInputBg: '#2a2a3a',
  addTaskNoteInputBorder: '#333',
  addTaskCountText: '#aaa',
  addTaskReminderText: '#aaa',
  // Tasks screen
  tasksContainerBg: '#0f0f1a',
  tasksHeaderBg: '#312e81',
  tasksIconBtnBg: '#1e1b4b',
  tasksSummaryTotalBg: '#1e1b4b',
  tasksSummaryCompletedBg: '#1a3a28',
  tasksSummaryTotalIconBg: '#312e81',
  tasksSummaryCompletedIconBg: '#1a3a28',
  tasksActiveFilterBg: '#6366f1',
  tasksTimeText: '#818cf8',
  tasksSearchBg: '#1e1e2e',
  tasksSearchBorder: '#3730a3',
  tasksSearchText: '#f0f0f0',
  tasksItemBg: '#1e1e2e',
  tasksItemBorder: '#333',
  tasksItemTitle: '#f0f0f0',
  tasksItemNote: '#aaa',
  tasksItemTime: '#888',
  tasksMenuBg: '#1e1e2e',
  tasksMenuBorder: '#333',
  tasksMenuText: '#f0f0f0',
  tasksEditModalBg: '#1e1e2e',
  tasksEditModalBorder: '#333',
  tasksEditModalTitle: '#f0f0f0',
  tasksEditInputBg: '#2a2a3a',
  tasksEditInputBorder: '#333',
  tasksEditInputText: '#f0f0f0',
  tasksModalSaveBg: '#312e81',
  // Edit Profile screen
  editProfileBg: '#0f0f1a',
  editProfileHeaderBg: '#1a1a2a',
  editProfileHeaderBorder: '#333',
  editProfileHeaderTitle: '#f0f0f0',
  editProfileBackBg: '#2a2a3a',
  editProfileGenderTitle: '#aaa',
  editProfileGenderCircleBg: '#2a2a3a',
  editProfileGenderText: '#ccc',
  // AI Scheduler screen
  aiContainerBg: '#0f0f1a',
  aiCardBg: '#312e81',
  aiCardBorder: '#4338ca',
  aiText: '#f0f0f0',
  aiSubText: '#c7d2fe',
  aiHintBg: '#1e1b4b',
  aiHintText: '#a5b4fc',
  aiTaskCountBg: '#1e3a5f',
  aiTaskCountText: '#a5b4fc',
  aiConfirmBtn: '#6366f1',
  aiIconWrapBg: '#1e1b4b',
  aiDraggingCardBg: '#1e1b4b',
  aiConfidenceFill: '#818cf8',
  aiConfidenceText: '#a5b4fc',
};

type ThemeContextType = {
  isDarkMode: boolean;
  toggleDarkMode: () => void;
  theme: typeof lightTheme;
};

const DARK_MODE_KEY = 'dark_mode_enabled';

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export function ThemeProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isDarkMode, setIsDarkMode] = useState(false);

  useEffect(() => {
    const loadTheme = async () => {
      try {
        const value = await AsyncStorage.getItem(DARK_MODE_KEY);
        if (value === 'true') {
          setIsDarkMode(true);
        }
      } catch (error) {
        console.error('Failed to load theme:', error);
      }
    };

    loadTheme();
  }, []);

  const toggleDarkMode = async () => {
    try {
      const newValue = !isDarkMode;
      setIsDarkMode(newValue);
      await AsyncStorage.setItem(DARK_MODE_KEY, String(newValue));
    } catch (error) {
      console.error('Failed to save theme:', error);
    }
  };

  const theme = isDarkMode ? darkTheme : lightTheme;

  return (
    <ThemeContext.Provider
      value={{
        isDarkMode,
        toggleDarkMode,
        theme,
      }}
    >
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme() {
  const context = useContext(ThemeContext);

  if (!context) {
    throw new Error('useTheme must be used within ThemeProvider');
  }

  return context;
}
