import React, { createContext, useContext, useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

type ThemeContextType = {
  isDarkMode: boolean;
  toggleDarkMode: () => void;
  theme: typeof lightTheme;
};

export const lightTheme = {
  isDark: false,
  bg: '#fafafa',
  cardBg: '#fff',
  text: '#111',
  subText: '#555',
  border: '#eee',
  inputBg: '#f5f5f5',
  headerBg: '#fff',
  sectionTitle: '#888',
  itemBg: '#fff',
  iconColor: '#444',
  switchTrackOff: '#ddd',
  switchTrackOn: '#c68be9',
  statCardTotal: '#1a1a2e',
  statCardCompleted: '#1a472a',
  statCardPending: '#5a2d00',
  statCardMissed: '#5a0a0a',
  // Home screen
  topBg: '#efc9f6',
  menuButtonBg: '#fff',
  menuButtonBorder: '#ececec',
  helloText: '#111',
  statTotal: '#fff',
  statCompleted: '#dff8de',
  statPending: '#dff3ff',
  statMissed: '#ffd7d7',
  statNumber: '#111',
  statLabel: '#333',
  progressCardBg: '#fff',
  progressTitle: '#111',
  progressSubText: '#666',
  progressBadgeBg: '#f3e1fb',
  progressBarTrack: '#f1e5f7',
  calendarCardBg: '#fff',
  calendarTitle: '#111',
  dateChipBg: '#faf7fb',
  dateChipBorder: '#f0e4f5',
  mainCardBg: '#e8c4ef',
  cardTitleText: '#111',
  cardDateText: '#555',
  aiPillBg: '#f8eab4',
  aiPillText: '#111',
  addPillBg: '#fff',
  addPillText: '#111',
  filterChipBg: 'rgba(255,255,255,0.58)',
  filterChipBorder: 'rgba(17,17,17,0.08)',
  filterText: '#111',
  taskCardBg: '#fff',
  taskCardBorder: '#ececec',
  taskTitle: '#111',
  taskTime: '#666',
  tipCardBg: '#fff',
  tipCardBorder: '#ececec',
  tipTitle: '#111',
  tipText: '#555',
  emptyCardBg: '#fff',
  emptyCardBorder: '#ececec',
  emptyTitle: '#111',
  emptyText: '#666',
  modalSheetBg: '#fff',
  modalTitle: '#111',
  weekHeaderText: '#777',
  dayNumber: '#111',
  otherMonthText: '#bbb',
  legendText: '#666',
  selectedTasksBg: '#faf7fb',
  selectedTasksBorder: '#f0e4f5',
  selectedTasksTitle: '#111',
  selectedTasksDate: '#666',
  modalTaskTitle: '#111',
  modalTaskTime: '#666',
  modalTaskBorder: '#eee',
  drawerBg: '#fff',
  menuItemBg: 'transparent',
  menuItemActiveBg: '#f3e9fb',
  menuIconWrapBg: '#f8f1fc',
  menuText: '#111',
  fabLabelBg: '#ffffff',
  fabLabelBorder: '#eadcf1',
  quickActionsBg: '#fff',
  quickActionsBorder: '#f0e6f5',
  quickActionText: '#111',
  quickActionIconBg: '#f8f1fc',
  // Today Plan screen
  planContainerBg: '#fff',
  planTopShapeBg: '#F4CCFF',
  planTitle: '#111',
  planSubtitle: '#666',
  dateCardBg: '#fff',
  dateCardBorder: '#E9D9EE',
  dateIconWrapBg: '#F4CCFF',
  dateLabel: '#777',
  dateValue: '#111',
  changeDateBtnBg: '#F9EDB8',
  changeDateBtnText: '#111',
  highlightCardBg: '#F4CCFF',
  highlightTitle: '#111',
  highlightText: '#444',
  percentBg: '#fff',
  percentValue: '#111',
  percentLabel: '#666',
  progressFill: '#111',
  calendarBg: '#FFFFFF',
  filterBorder: '#111',
  filterBg: '#fff',
  activeFilterBg: '#F4CCFF',
  timelineTime: '#666',
  timelineDot: '#111',
  timelineLine: '#DDD6E3',
  timelineCardBg: '#FCF7FD',
  timelineCardBorder: '#E9D9EE',
  iconBoxBg: '#F4CCFF',
  planTitleText: '#111',
  planNoteText: '#555',
  primaryBtnBg: '#fff',
  primaryBtnBorder: '#111',
  // Add Task screen
  addTaskContainerBg: '#FFF7FB',
  addTaskTopShape: '#F8DCEB',
  addTaskTitle: '#111',
  addTaskSubtitle: '#666',
  addTaskCardBg: '#fff',
  addTaskCardBorder: '#EFE7ED',
  addTaskCardTitle: '#111',
  addTaskIconBoxBg: '#fff3f8',
  addTaskInputBg: '#FFFFFF',
  addTaskInputBorder: '#E8E3E7',
  addTaskInputText: '#111',
  addTaskFieldLabel: '#444',
  addTaskChipBg: '#fff',
  addTaskChipBorder: '#D8D4D9',
  addTaskChipText: '#111',
  addTaskNoteInputBg: '#fff',
  addTaskNoteInputBorder: '#E8E3E7',
  addTaskCountText: '#777',
  addTaskReminderText: '#555',
  // Tasks screen
  tasksContainerBg: '#f8f5fc',
  tasksHeaderBg: '#1a0030',
  tasksSearchBg: '#fff',
  tasksSearchBorder: '#ede9f5',
  tasksSearchText: '#111',
  tasksItemBg: '#fff',
  tasksItemBorder: '#ede9f5',
  tasksItemTitle: '#111',
  tasksItemNote: '#666',
  tasksItemTime: '#888',
  tasksMenuBg: '#fff',
  tasksMenuBorder: '#ede9f5',
  tasksMenuText: '#111',
  tasksEditModalBg: '#fff',
  tasksEditModalBorder: '#ede9f5',
  tasksEditModalTitle: '#111',
  tasksEditInputBg: '#f8f5fc',
  tasksEditInputBorder: '#ede9f5',
  tasksEditInputText: '#111',
  // Edit Profile screen
  editProfileBg: '#fafafa',
  editProfileHeaderBg: '#fff',
  editProfileHeaderBorder: '#eee',
  editProfileHeaderTitle: '#111',
  editProfileBackBg: '#f5f5f5',
  editProfileGenderTitle: '#555',
  editProfileGenderCircleBg: '#e8e8e8',
  editProfileGenderText: '#333',
  // AI Scheduler screen
  aiContainerBg: '#1a0030',
  aiCardBg: '#2c1a4a',
  aiCardBorder: '#3d2460',
  aiText: '#f0e6ff',
  aiSubText: '#b89dd4',
};

export const darkTheme = {
  isDark: true,
  bg: '#0f0f1a',
  cardBg: '#1e1e2e',
  text: '#f0f0f0',
  subText: '#aaa',
  border: '#333',
  inputBg: '#2a2a3a',
  headerBg: '#1a1a2a',
  sectionTitle: '#999',
  itemBg: '#1e1e2e',
  iconColor: '#bbb',
  switchTrackOff: '#444',
  switchTrackOn: '#c68be9',
  statCardTotal: '#2a2a4a',
  statCardCompleted: '#1a3a28',
  statCardPending: '#3a2000',
  statCardMissed: '#3a0a0a',
  // Home screen
  topBg: '#2a1040',
  menuButtonBg: '#1e1e2e',
  menuButtonBorder: '#333',
  helloText: '#f0f0f0',
  statTotal: '#1e1e2e',
  statCompleted: '#1a3a28',
  statPending: '#0a2a3a',
  statMissed: '#3a0a0a',
  statNumber: '#f0f0f0',
  statLabel: '#ccc',
  progressCardBg: '#1e1e2e',
  progressTitle: '#f0f0f0',
  progressSubText: '#999',
  progressBadgeBg: '#2a1040',
  progressBarTrack: '#2a1a3a',
  calendarCardBg: '#1e1e2e',
  calendarTitle: '#f0f0f0',
  dateChipBg: '#2a2a3a',
  dateChipBorder: '#333',
  mainCardBg: '#2a1040',
  cardTitleText: '#f0f0f0',
  cardDateText: '#aaa',
  aiPillBg: '#3a2a10',
  aiPillText: '#f0f0f0',
  addPillBg: '#2a2a3a',
  addPillText: '#f0f0f0',
  filterChipBg: 'rgba(255,255,255,0.08)',
  filterChipBorder: 'rgba(255,255,255,0.12)',
  filterText: '#f0f0f0',
  taskCardBg: '#1e1e2e',
  taskCardBorder: '#333',
  taskTitle: '#f0f0f0',
  taskTime: '#aaa',
  tipCardBg: '#1e1e2e',
  tipCardBorder: '#333',
  tipTitle: '#f0f0f0',
  tipText: '#aaa',
  emptyCardBg: '#1e1e2e',
  emptyCardBorder: '#333',
  emptyTitle: '#f0f0f0',
  emptyText: '#aaa',
  modalSheetBg: '#1a1a2a',
  modalTitle: '#f0f0f0',
  weekHeaderText: '#888',
  dayNumber: '#f0f0f0',
  otherMonthText: '#555',
  legendText: '#aaa',
  selectedTasksBg: '#1e1e2e',
  selectedTasksBorder: '#333',
  selectedTasksTitle: '#f0f0f0',
  selectedTasksDate: '#aaa',
  modalTaskTitle: '#f0f0f0',
  modalTaskTime: '#aaa',
  modalTaskBorder: '#333',
  drawerBg: '#1a1a2a',
  menuItemBg: 'transparent',
  menuItemActiveBg: '#2a1040',
  menuIconWrapBg: '#2a2a3a',
  menuText: '#f0f0f0',
  fabLabelBg: '#1e1e2e',
  fabLabelBorder: '#333',
  quickActionsBg: '#1e1e2e',
  quickActionsBorder: '#333',
  quickActionText: '#f0f0f0',
  quickActionIconBg: '#2a2a3a',
  // Today Plan screen
  planContainerBg: '#0f0f1a',
  planTopShapeBg: '#2a1040',
  planTitle: '#f0f0f0',
  planSubtitle: '#aaa',
  dateCardBg: '#1e1e2e',
  dateCardBorder: '#333',
  dateIconWrapBg: '#2a1040',
  dateLabel: '#aaa',
  dateValue: '#f0f0f0',
  changeDateBtnBg: '#3a2a10',
  changeDateBtnText: '#f0f0f0',
  highlightCardBg: '#2a1040',
  highlightTitle: '#f0f0f0',
  highlightText: '#bbb',
  percentBg: '#1e1e2e',
  percentValue: '#f0f0f0',
  percentLabel: '#aaa',
  progressFill: '#c68be9',
  calendarBg: '#1e1e2e',
  filterBorder: '#555',
  filterBg: '#1e1e2e',
  activeFilterBg: '#2a1040',
  timelineTime: '#aaa',
  timelineDot: '#c68be9',
  timelineLine: '#333',
  timelineCardBg: '#1e1e2e',
  timelineCardBorder: '#333',
  iconBoxBg: '#2a1040',
  planTitleText: '#f0f0f0',
  planNoteText: '#aaa',
  primaryBtnBg: '#1e1e2e',
  primaryBtnBorder: '#555',
  // Add Task screen
  addTaskContainerBg: '#0f0f1a',
  addTaskTopShape: '#2a1040',
  addTaskTitle: '#f0f0f0',
  addTaskSubtitle: '#aaa',
  addTaskCardBg: '#1e1e2e',
  addTaskCardBorder: '#333',
  addTaskCardTitle: '#f0f0f0',
  addTaskIconBoxBg: '#2a1040',
  addTaskInputBg: '#2a2a3a',
  addTaskInputBorder: '#333',
  addTaskInputText: '#f0f0f0',
  addTaskFieldLabel: '#bbb',
  addTaskChipBg: '#2a2a3a',
  addTaskChipBorder: '#444',
  addTaskChipText: '#f0f0f0',
  addTaskNoteInputBg: '#2a2a3a',
  addTaskNoteInputBorder: '#333',
  addTaskCountText: '#aaa',
  addTaskReminderText: '#aaa',
  // Tasks screen
  tasksContainerBg: '#0f0f1a',
  tasksHeaderBg: '#0a0015',
  tasksSearchBg: '#1e1e2e',
  tasksSearchBorder: '#333',
  tasksSearchText: '#f0f0f0',
  tasksItemBg: '#1e1e2e',
  tasksItemBorder: '#333',
  tasksItemTitle: '#f0f0f0',
  tasksItemNote: '#aaa',
  tasksItemTime: '#888',
  tasksMenuBg: '#1e1e2e',
  tasksMenuBorder: '#333',
  tasksMenuText: '#f0f0f0',
  tasksEditModalBg: '#1e1e2e',
  tasksEditModalBorder: '#333',
  tasksEditModalTitle: '#f0f0f0',
  tasksEditInputBg: '#2a2a3a',
  tasksEditInputBorder: '#333',
  tasksEditInputText: '#f0f0f0',
  // Edit Profile screen
  editProfileBg: '#0f0f1a',
  editProfileHeaderBg: '#1a1a2a',
  editProfileHeaderBorder: '#333',
  editProfileHeaderTitle: '#f0f0f0',
  editProfileBackBg: '#2a2a3a',
  editProfileGenderTitle: '#aaa',
  editProfileGenderCircleBg: '#2a2a3a',
  editProfileGenderText: '#ccc',
  // AI Scheduler screen
  aiContainerBg: '#0f0f1a',
  aiCardBg: '#1e1e2e',
  aiCardBorder: '#333',
  aiText: '#f0f0f0',
  aiSubText: '#aaa',
};

const DARK_MODE_KEY = 'dark_mode_enabled';

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export function ThemeProvider({ children }: { children: React.ReactNode }) {
  const [isDarkMode, setIsDarkMode] = useState(false);

  useEffect(() => {
    // Load saved preference
    AsyncStorage.getItem(DARK_MODE_KEY).then((val) => {
      if (val === 'true') setIsDarkMode(true);
    });
  }, []);

  const toggleDarkMode = async () => {
    const newVal = !isDarkMode;
    setIsDarkMode(newVal);
    await AsyncStorage.setItem(DARK_MODE_KEY, String(newVal));
  };

  const theme = isDarkMode ? darkTheme : lightTheme;

  return (
    <ThemeContext.Provider value={{ isDarkMode, toggleDarkMode, theme }}>
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme() {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error('useTheme must be used inside ThemeProvider');
  }
  return context;
}
